import os
from openai import AzureOpenAI

# Read config.txt
with open("config.txt", "r") as f:
    lines = f.read().strip().split("\n")
    for line in lines:
        if line.startswith("API_KEY:"):
            subscription_key = line.split("API_KEY:")[1]
        elif line.startswith("LANGCHAIN_API_KEY:"):
            os.environ["LANGCHAIN_API_KEY"] = line.split("LANGCHAIN_API_KEY:")[1]
        elif "LANGCHAIN_TRACING_V2" in line:
            os.environ["LANGCHAIN_TRACING_V2"] = "true"
        elif "LANGCHAIN_PROJECT" in line:
            os.environ["LANGCHAIN_PROJECT"] = line.split("=")[1]

# Initialize Azure OpenAI Client
endpoint = "https://dfran-m6zqnnwy-eastus2.cognitiveservices.azure.com/"
api_version = "2024-12-01-preview"

client = AzureOpenAI(
    api_version=api_version,
    azure_endpoint=endpoint,
    api_key=subscription_key
) 

# The Persona
SYSTEM_PROMPT = """
You are an expert Cloud Engineer specializing in AWS and Terraform. 
Your goal is to write executable Terraform code based on user requests.
IMPORTANT:
1. Output ONLY the code. Do not use Markdown backticks (```hcl). 
2. Do not write explanations. Just the code.
"""

def generate_terraform(user_request):
    print(f"🤖 Agent is thinking about: '{user_request}'...")
    
    response = client.chat.completions.create(
        model="gpt-4o-mini", # Azure deployment name
        messages=[
            {"role": "system", "content": SYSTEM_PROMPT},
            {"role": "user", "content": user_request}
        ],
        temperature=0 # Keep it deterministic for code
    )
    
    code = response.choices[0].message.content
    
    # Clean up markdown just in case the LLM disobeys
    code = code.replace("```hcl", "").replace("```", "").strip()
    return code

if __name__ == "__main__":
    # Test Request
    request = "Create a local file named 'agent_test.txt' with content 'Generated by Python!'"
    
    # 1. Generate
    terraform_code = generate_terraform(request)
    
    # 2. Save to file
    with open("main.tf", "w") as f:
        f.write(terraform_code)
    
    print("✅ Terraform code generated and saved to main.tf")
    print("------------------------------------------------")
    print(terraform_code)
    print("------------------------------------------------")